export const conceptTopics = [
  {
    id: 'arrays',
    name: 'Arrays',
    group: 'Data Structures',
    visualType: 'array',
    summary: 'Contiguous indexed storage for fast lookup and simple traversal.',
    complexity: 'Access O(1), Search O(n), Insert/Delete O(n)',
  },
  {
    id: 'strings',
    name: 'Strings',
    group: 'Data Structures',
    visualType: 'array',
    summary: 'Character sequences where indexing, matching, and scanning patterns matter.',
    complexity: 'Access O(1), Scan O(n), Pattern matching varies',
  },
  {
    id: 'linked-lists',
    name: 'Linked Lists',
    group: 'Data Structures',
    visualType: 'chain',
    summary: 'Nodes connected by pointers, useful when frequent insertion is needed.',
    complexity: 'Search O(n), Insert after node O(1), Delete after node O(1)',
  },
  {
    id: 'stacks',
    name: 'Stacks',
    group: 'Data Structures',
    visualType: 'stack',
    summary: 'Last-in, first-out structure for undo, parsing, recursion, and backtracking.',
    complexity: 'Push O(1), Pop O(1), Peek O(1)',
  },
  {
    id: 'queues',
    name: 'Queues',
    group: 'Data Structures',
    visualType: 'queue',
    summary: 'First-in, first-out structure for scheduling and breadth-first traversal.',
    complexity: 'Enqueue O(1), Dequeue O(1), Peek O(1)',
  },
  {
    id: 'trees',
    name: 'Trees',
    group: 'Data Structures',
    visualType: 'tree',
    summary: 'Hierarchical nodes with parent-child relationships.',
    complexity: 'Traversal O(n), Search depends on tree shape',
  },
  {
    id: 'bst',
    name: 'BST',
    group: 'Data Structures',
    visualType: 'tree',
    summary: 'Binary search tree keeps smaller values left and larger values right.',
    complexity: 'Average Search/Insert/Delete O(log n), Worst O(n)',
  },
  {
    id: 'avl',
    name: 'AVL',
    group: 'Data Structures',
    visualType: 'tree',
    summary: 'Self-balancing BST that uses rotations to keep height small.',
    complexity: 'Search/Insert/Delete O(log n)',
  },
  {
    id: 'heap',
    name: 'Heap',
    group: 'Data Structures',
    visualType: 'heap',
    summary: 'Complete tree optimized for repeatedly finding min or max priority.',
    complexity: 'Peek O(1), Insert O(log n), Extract O(log n)',
  },
  {
    id: 'trie',
    name: 'Trie',
    group: 'Data Structures',
    visualType: 'trie',
    summary: 'Prefix tree for storing strings and answering prefix queries.',
    complexity: 'Search/Insert O(length of word)',
  },
  {
    id: 'graphs',
    name: 'Graphs',
    group: 'Data Structures',
    visualType: 'graph',
    summary: 'Vertices and edges model networks, dependencies, and paths.',
    complexity: 'Traversal O(V + E)',
  },
  {
    id: 'searching',
    name: 'Searching',
    group: 'Algorithms',
    visualType: 'array',
    summary: 'Find target values using scans, ordering, or structure-aware lookup.',
    complexity: 'Linear O(n), Binary O(log n) on sorted data',
  },
  {
    id: 'sorting',
    name: 'Sorting',
    group: 'Algorithms',
    visualType: 'bars',
    summary: 'Rearrange data into order to make later processing easier.',
    complexity: 'Common comparison sorts O(n log n)',
  },
  {
    id: 'bfs',
    name: 'BFS',
    group: 'Graph Algorithms',
    visualType: 'graph',
    summary: 'Explores neighbors level by level using a queue.',
    complexity: 'O(V + E)',
  },
  {
    id: 'dfs',
    name: 'DFS',
    group: 'Graph Algorithms',
    visualType: 'graph',
    summary: 'Explores deeply before backtracking, often using recursion or a stack.',
    complexity: 'O(V + E)',
  },
  {
    id: 'dijkstra',
    name: 'Dijkstra',
    group: 'Graph Algorithms',
    visualType: 'weighted-graph',
    summary: 'Finds shortest paths from a source when edge weights are non-negative.',
    complexity: 'O((V + E) log V) with a priority queue',
  },
  {
    id: 'dynamic-programming',
    name: 'Dynamic Programming',
    group: 'Patterns',
    visualType: 'grid',
    summary: 'Breaks problems into overlapping subproblems and stores answers.',
    complexity: 'Usually states multiplied by transitions',
  },
  {
    id: 'greedy',
    name: 'Greedy',
    group: 'Patterns',
    visualType: 'choice',
    summary: 'Builds a solution by repeatedly taking the best local choice.',
    complexity: 'Depends on sorting, heap usage, or scan strategy',
  },
  {
    id: 'recursion',
    name: 'Recursion',
    group: 'Patterns',
    visualType: 'recursion',
    summary: 'Solves a problem by calling the same logic on smaller inputs.',
    complexity: 'Depends on branching factor and depth',
  },
  {
    id: 'backtracking',
    name: 'Backtracking',
    group: 'Patterns',
    visualType: 'backtracking',
    summary: 'Searches possibilities, abandoning invalid partial solutions early.',
    complexity: 'Often exponential, improved by pruning',
  },
]

export function getConceptTopic(topicId) {
  return conceptTopics.find((topic) => topic.id === topicId) ?? conceptTopics[0]
}
